Us1
WildCodeSchool-2024-02/JS-bdx-0224-P2-cocktail_club pull request #6
Opened 2024-04-16 13:51 UTC by FranckWebPro

2024-04-16 14:26 UTC, Yoann-Fortin requested changes

2024-04-16 14:26 UTC, Yoann-Fortin commented on client/src/components/CocktailCard.jsx
A ghost component ? Where is this logic ?

2024-04-16 14:26 UTC, Yoann-Fortin commented on client/src/components/OrangeButton.jsx
> +      <p className="season">{season}</p>
Isn't possible, check W3C validator

2024-04-16 14:26 UTC, Yoann-Fortin commented on client/src/components/OrangeButton.jsx
> +function OrangeButton({ season }) {
Name isn't the real call to action

2024-04-16 14:26 UTC, Yoann-Fortin commented on client/src/styles/CocktailsSection.css
No empty file please

2024-04-16 14:26 UTC, Yoann-Fortin commented on client/src/styles/SeasonCard.css
> +:root {
is already defined

2024-04-16 14:26 UTC, Yoann-Fortin commented on client/src/styles/SeasonCard.css
> +  min-height: calc(50vh);
calc is overkill

2024-04-16 14:26 UTC, Yoann-Fortin commented on client/src/styles/OrangeButton.css
No empty file please

2024-04-17 08:40 UTC, Yoann-Fortin requested changes

2024-04-17 08:40 UTC, Yoann-Fortin commented on client/src/components/OrangeButton.jsx
> +function OrangeButton({ season }) {
This isn't change yet

2024-04-17 12:08 UTC, Yoann-Fortin approved these changes

2024-04-17 13:05 UTC, Yoann-Fortin requested changes

2024-04-17 13:05 UTC, Yoann-Fortin commented on client/src/components/OrangeLink.jsx
> +    <a
With Link and generic props please

2024-04-18 13:48 UTC, Yoann-Fortin requested changes

2024-04-18 13:48 UTC, Yoann-Fortin commented on client/src/components/CocktailPage.jsx
Commented code is not possible

2024-04-19 16:21 UTC, Yoann-Fortin approved these changes

2024-04-22 13:40 UTC, JulienChevreauPro commented on client/src/pages/CocktailPage.jsx
> -  return <p>dsfh</p>;
what is dsfh?

2024-04-22 13:42 UTC, JulienChevreauPro requested changes

2024-04-22 13:42 UTC, JulienChevreauPro commented on client/src/pages/CocktailPage.jsx
comments

2024-04-22 14:00 UTC, JulienChevreauPro approved these changes

2024-04-22 14:01 UTC, merged