Loader
WildCodeSchool-2024-02/JS-bdx-0224-P2-cocktail_club pull request #9
Opened 2024-04-19 09:28 UTC by FranckWebPro

2024-04-19 16:16 UTC, Yoann-Fortin requested changes

2024-04-19 16:16 UTC, Yoann-Fortin commented on client/src/App.jsx
> +    <div className="pageWrapper">
Why use a div tag here?

2024-04-22 14:27 UTC, JulienChevreauPro approved these changes

2024-04-22 15:26 UTC, Yoann-Fortin approved these changes

2024-04-22 15:26 UTC, merged